AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Resources:
  MyFirstFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Runtime: python3.10
      CodeUri: .
      Environment:
        Variables:
          PYTHONPATH: ./venv/lib/python3.10/site-packages
      Events:
        PostRequest:
          Type: Api
          Properties:
            Path: /save
            Method: post
